name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Docker Image Name'
        required: false
      image_tag:
        description: 'Docker Image Tag (Version)'
        required: false
        default: 'latest'

env:
  SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}

#permissions:
 # contents: read
  #packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from version.py
        id: get_version
        run: echo "VERSION=$(grep 'VERSION' version.py | cut -d '=' -f2 | tr -d ' \"')" >> $GITHUB_ENV

      - name: Extract Commit SHA
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set Image Name
        run: |
          IMAGE_NAME=${{ github.event.inputs.image_name }}
          if [[ -z "$IMAGE_NAME" ]]; then
            IMAGE_NAME="${{ secrets.IMAGE_NAME }}"
          fi
          echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker Image with Commit SHA
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG-$SHORT_SHA .

      - name: Push Docker Image to GHCR
        run: |
          IMAGE_TAG=${{ github.event.inputs.image_tag || 'latest' }}
          docker push $IMAGE_NAME:$IMAGE_TAG-$SHORT_SHA

      - name: Notify Microsoft Teams on Success
        if: success()
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        with:
          args: "✅ *GitHub Actions:* Build & Push Successful!\n\n*Image:* `$IMAGE_NAME:${{ github.event.inputs.image_tag || 'latest' }}-$SHORT_SHA` successfully pushed to GHCR."

      - name: Notify Microsoft Teams on Failure
        if: failure()
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        with:
          args: "❌ *GitHub Actions:* Build & Push Failed!\n\nPlease check the logs."
