name: Build and Push to GHCR

on:
  push:
    branches:
      - main
      - test
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: false
        default: 'latest'

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ secrets.IMAGE_NAME }}
  SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug IMAGE_NAME
        run: echo "IMAGE_NAME is: $IMAGE_NAME"

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:${{ github.event.inputs.image_tag || 'latest' }} .

      - name: Push Docker Image to GHCR
        run: docker push $IMAGE_NAME:${{ github.event.inputs.image_tag || 'latest' }}

      - name: Notify Microsoft Teams on Success
        if: success()
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        with:
          args: "✅ *GitHub Actions:* Build & Push Successful!\n\n*Image:* `$IMAGE_NAME:${{ github.event.inputs.image_tag || 'latest' }}` successfully pushed to GHCR."

      - name: Notify Microsoft Teams on Failure
        if: failure()
        uses: Ilshidur/action-slack@master
        env:
          SLACK_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
        with:
          args: "❌ *GitHub Actions:* Build & Push Failed!\n\nPlease check the logs."
